### ISSUE TITLE
Compile problem

### ISSUE THREAD

**Issue by dalb8** [communitymedia/mediautilities#1]
I'm trying to build the Mediaphone app. In mediautilities, I ran: cd jni && OPENCORE_AMR_PATH=$(readlink -f ../fdk-aac-0.1.3) NDK_PATH=~/android-ndk-r9/ PROJECT_PATH=$(readlink -f ..) ./build.sh

but I get.

Android NDK: ERROR:/home/gerry/fdroiddata/build/srclib/MediaUtilities/external/opencore-amr/Android.mk:opencore-amrnb: LOCAL_SRC_FILES points to a missing file  
Android NDK: Check that /home/gerry/fdroiddata/build/srclib/MediaUtilities/external/opencore-amr/lib/libopencore-amrnb.a exists  or that its path is correct  
/home/gerry/android-ndk-r9/build/core/prebuilt-library.mk:45: **\* Android NDK: Aborting    .  Stop.

**Comment by simonrob** [comment]
@dalb8 - for some reason I didn't get notified when this issue was posted, and I'm presuming you've since moved on, or got things working yourself. Sorry about this!

The latest commits have moved the mediaphone/mediautilities projects to Android Studio, fixed several issues and generally modernised things. As a result, it should be much easier to import the project and build it yourself.

Turing to this issue in particular, the repository includes the compiled version of the native code so that you shouldn't have to build it yourself - the idea was to avoid issues like this. If you do still want to do this three years later (!), or want to modify the native code so need to build it yourself and still run into problems, feel free to reopen this issue and I'll look into it further.
